-- SCHEMA_BASELINE.sql
-- SQEPify schema snapshot. Reference of record.
-- Baseline established: Foundations step (initial).
-- Regenerated by re-extraction (see EXTRACTION_QUERIES.sql), never hand-edited per change.
--
-- This snapshot reflects the database after the Foundations step only.
-- Later tables (consultants, competencies, trainings, assessments, cases, plans)
-- are added in later build-order steps and captured at the next re-baseline.
--
-- Object order matters: the users table is created before the is_superadmin()
-- helper (which reads it), and the helper before the policies (which call it).

-- ============================================================
-- users
-- ============================================================
create table if not exists public.users (
  id            uuid primary key default gen_random_uuid(),
  email         text not null,
  full_name     text,
  product_role  text not null default 'consultant'
                check (product_role in ('superadmin', 'technical_director', 'consultant')),
  consultant_id text,  -- links to the cached consultant record (added in a later step)
  is_active     boolean not null default true,
  created_at    timestamptz not null default now()
);

-- Case-insensitive uniqueness on email (identity is matched by email).
create unique index if not exists users_email_lower_idx
  on public.users (lower(email));

-- ============================================================
-- app_settings (single row: AI provider and model)
-- ============================================================
create table if not exists public.app_settings (
  id          boolean primary key default true check (id),  -- enforces a single row
  ai_provider text not null default 'anthropic'
              check (ai_provider in ('anthropic', 'openai')),
  ai_model    text not null default 'claude-sonnet-4-20250514',
  updated_at  timestamptz not null default now()
);

insert into public.app_settings (id) values (true)
on conflict (id) do nothing;

-- ============================================================
-- Helper: is the caller a superadmin?
-- SECURITY DEFINER so it can read the users table without tripping the table's
-- own RLS (which would otherwise recurse). Matches the caller by email claim.
-- Created after users exists.
-- ============================================================
create or replace function public.is_superadmin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.users u
    where lower(u.email) = lower(auth.jwt() ->> 'email')
      and u.product_role = 'superadmin'
      and u.is_active
  );
$$;

-- ============================================================
-- Row Level Security and policies (created after the helper exists)
-- ============================================================
alter table public.users enable row level security;

drop policy if exists users_select_self on public.users;
create policy users_select_self on public.users
  for select
  using (lower(email) = lower(auth.jwt() ->> 'email'));

drop policy if exists users_all_superadmin on public.users;
create policy users_all_superadmin on public.users
  for all
  using (public.is_superadmin())
  with check (public.is_superadmin());

alter table public.app_settings enable row level security;

drop policy if exists app_settings_select_auth on public.app_settings;
create policy app_settings_select_auth on public.app_settings
  for select
  using (auth.role() = 'authenticated');

drop policy if exists app_settings_write_superadmin on public.app_settings;
create policy app_settings_write_superadmin on public.app_settings
  for all
  using (public.is_superadmin())
  with check (public.is_superadmin());

-- ============================================================
-- consultants (local cache of active consultants from the Control Room feed)
-- Keyed off the Control Room id. Leavers are kept as history (is_active=false),
-- never deleted. Only the sync edge function writes here (service role).
-- ============================================================
create table if not exists public.consultants (
  id                 uuid primary key,
  full_name          text,
  first_name         text,
  last_name          text,
  email              text not null,
  company_email      text,
  job_title          text,
  status             text,
  engineering_skills text[] not null default '{}',
  td_id              uuid,
  td_full_name       text,
  td_email           text,
  is_active          boolean not null default true,
  first_seen_at      timestamptz not null default now(),
  last_seen_at       timestamptz not null default now(),
  left_at            timestamptz,
  updated_at         timestamptz not null default now()
);

create unique index if not exists consultants_company_email_unique
  on public.consultants (lower(company_email)) where company_email is not null;
create index if not exists consultants_td_email_idx on public.consultants (lower(td_email));
create index if not exists consultants_is_active_idx on public.consultants (is_active);

alter table public.consultants enable row level security;

drop policy if exists consultants_select_superadmin on public.consultants;
create policy consultants_select_superadmin on public.consultants
  for select using (public.is_superadmin());

drop policy if exists consultants_select_td on public.consultants;
create policy consultants_select_td on public.consultants
  for select using (lower(td_email) = lower(auth.jwt() ->> 'email'));

drop policy if exists consultants_select_self on public.consultants;
create policy consultants_select_self on public.consultants
  for select using (
    lower(coalesce(company_email, '')) = lower(auth.jwt() ->> 'email')
    or lower(email) = lower(auth.jwt() ->> 'email')
  );

-- ============================================================
-- sync_state (single row: when the consultant sync last ran successfully)
-- Written by the sync edge function (service role). Read-only to the app.
-- ============================================================
create table if not exists public.sync_state (
  id               boolean primary key default true check (id),
  last_sync_at     timestamptz,
  last_pulled      int,
  last_marked_left int,
  updated_at       timestamptz not null default now()
);
insert into public.sync_state (id) values (true) on conflict (id) do nothing;

alter table public.sync_state enable row level security;

drop policy if exists sync_state_select_auth on public.sync_state;
create policy sync_state_select_auth on public.sync_state
  for select using (auth.role() = 'authenticated');

-- ============================================================
-- reconcile_consultant_users()
-- Called at the end of each consultant sync. Creates a SQEPify login for each
-- active consultant that has a company email, links existing logins, reactivates
-- returning consultants, and switches off the logins of consultants who have left.
-- Only ever affects consultant-role accounts; never a TD or superadmin.
-- ============================================================
create or replace function public.reconcile_consultant_users()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (email, full_name, product_role, is_active, consultant_id)
  select c.company_email, c.full_name, 'consultant', true, c.id::text
  from public.consultants c
  where c.is_active
    and c.company_email is not null
    and not exists (select 1 from public.users u where lower(u.email) = lower(c.company_email));

  update public.users u
  set consultant_id = c.id::text,
      is_active = case when u.product_role = 'consultant' then true else u.is_active end
  from public.consultants c
  where c.is_active and c.company_email is not null
    and lower(u.email) = lower(c.company_email);

  update public.users u
  set is_active = false
  from public.consultants c
  where u.product_role = 'consultant'
    and u.consultant_id = c.id::text
    and c.is_active = false;
end;
$$;

-- ============================================================
-- is_staff(): caller is a superadmin or a technical director (active)
-- ============================================================
create or replace function public.is_staff()
returns boolean language sql security definer set search_path = public as $$
  select exists (
    select 1 from public.users u
    where lower(u.email) = lower(auth.jwt() ->> 'email')
      and u.product_role in ('superadmin','technical_director')
      and u.is_active
  );
$$;

-- ============================================================
-- trainers (approved trainers registry: TDs, consultants, external providers)
-- A training may only list deliverers that appear here.
-- ============================================================
create table if not exists public.trainers (
  id            uuid primary key default gen_random_uuid(),
  kind          text not null check (kind in ('technical_director','consultant','external')),
  user_id       uuid,
  consultant_id text,
  display_name  text not null,
  company_name  text,
  contact_name  text,
  contact_email text,
  contact_phone text,
  notes         text,
  is_active     boolean not null default true,
  created_at    timestamptz not null default now()
);
create unique index if not exists trainers_user_unique on public.trainers (user_id) where user_id is not null;
create unique index if not exists trainers_consultant_unique on public.trainers (consultant_id) where consultant_id is not null;

alter table public.trainers enable row level security;

drop policy if exists trainers_select_staff on public.trainers;
create policy trainers_select_staff on public.trainers for select using (public.is_staff());

drop policy if exists trainers_write_superadmin on public.trainers;
drop policy if exists trainers_write_staff on public.trainers;
create policy trainers_write_staff on public.trainers
  for all using (public.is_staff()) with check (public.is_staff());

-- Guarded lookup so staff can pick trainers without the user/consultant tables being opened up
create or replace function public.trainer_candidates()
returns table (kind text, id text, name text)
language sql security definer set search_path = public as $$
  select 'td'::text, u.id::text, coalesce(u.full_name, u.email)
  from public.users u
  where public.is_staff() and u.product_role = 'technical_director' and u.is_active
  union all
  select 'consultant'::text, c.id::text, coalesce(c.full_name, c.company_email, c.email)
  from public.consultants c
  where public.is_staff() and c.is_active;
$$;
grant execute on function public.trainer_candidates() to authenticated;

-- ============================================================
-- Competency taxonomy: category -> optional subcategory -> competency
-- Read: any signed-in user. Write: staff (superadmin or technical director).
-- ============================================================
create table if not exists public.competency_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists public.competency_subcategories (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.competency_categories(id) on delete cascade,
  name text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists public.competencies (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.competency_categories(id) on delete cascade,
  subcategory_id uuid references public.competency_subcategories(id) on delete set null,
  name text not null,
  description text,
  level_descriptors jsonb,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists competency_subcategories_category on public.competency_subcategories(category_id);
create index if not exists competencies_category on public.competencies(category_id);
create index if not exists competencies_subcategory on public.competencies(subcategory_id);

alter table public.competency_categories enable row level security;
alter table public.competency_subcategories enable row level security;
alter table public.competencies enable row level security;

drop policy if exists comp_cat_read on public.competency_categories;
create policy comp_cat_read on public.competency_categories for select using (public.is_staff());
drop policy if exists comp_cat_write on public.competency_categories;
create policy comp_cat_write on public.competency_categories for all using (public.is_staff()) with check (public.is_staff());

drop policy if exists comp_sub_read on public.competency_subcategories;
create policy comp_sub_read on public.competency_subcategories for select using (public.is_staff());
drop policy if exists comp_sub_write on public.competency_subcategories;
create policy comp_sub_write on public.competency_subcategories for all using (public.is_staff()) with check (public.is_staff());

drop policy if exists comp_read on public.competencies;
create policy comp_read on public.competencies for select using (public.is_staff());
drop policy if exists comp_write on public.competencies;
create policy comp_write on public.competencies for all using (public.is_staff()) with check (public.is_staff());

-- ============================================================
-- Roles: named sets of competencies. Base Nuclear is the always-present base.
-- A competency in Base cannot be in any other role (and vice versa); normal roles
-- may share competencies. Read: staff. Write: staff. Base role is protected.
-- ============================================================
create table if not exists public.roles (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  is_base boolean not null default false,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);
create unique index if not exists roles_single_base on public.roles ((is_base)) where is_base;

create table if not exists public.role_competencies (
  role_id uuid not null references public.roles(id) on delete cascade,
  competency_id uuid not null references public.competencies(id) on delete cascade,
  required_level int not null default 4 check (required_level between 1 and 5),
  created_at timestamptz not null default now(),
  primary key (role_id, competency_id)
);

create or replace function public.protect_base_role() returns trigger language plpgsql as $$
begin
  if tg_op = 'DELETE' then
    if old.is_base then raise exception 'The Base Nuclear role cannot be deleted.'; end if;
    return old;
  end if;
  if old.is_base and not new.is_base then raise exception 'The Base Nuclear role must remain the base.'; end if;
  return new;
end $$;
drop trigger if exists trg_protect_base_role on public.roles;
create trigger trg_protect_base_role before update or delete on public.roles
  for each row execute function public.protect_base_role();

create or replace function public.enforce_role_exclusivity() returns trigger language plpgsql as $$
declare target_is_base boolean;
begin
  select is_base into target_is_base from public.roles where id = new.role_id;
  if target_is_base then
    if exists (select 1 from public.role_competencies rc join public.roles r on r.id = rc.role_id
               where rc.competency_id = new.competency_id and not r.is_base) then
      raise exception 'This competency is in a role already; remove it before adding to Base Nuclear.';
    end if;
  else
    if exists (select 1 from public.role_competencies rc join public.roles r on r.id = rc.role_id
               where rc.competency_id = new.competency_id and r.is_base) then
      raise exception 'This competency is in Base Nuclear and cannot be added to a role.';
    end if;
  end if;
  return new;
end $$;
drop trigger if exists trg_role_exclusivity on public.role_competencies;
create trigger trg_role_exclusivity before insert on public.role_competencies
  for each row execute function public.enforce_role_exclusivity();

alter table public.roles enable row level security;
alter table public.role_competencies enable row level security;
drop policy if exists roles_read on public.roles;
create policy roles_read on public.roles for select using (public.is_staff());
drop policy if exists roles_write on public.roles;
create policy roles_write on public.roles for all using (public.is_staff()) with check (public.is_staff());
drop policy if exists rc_read on public.role_competencies;
create policy rc_read on public.role_competencies for select using (public.is_staff());
drop policy if exists rc_write on public.role_competencies;
create policy rc_write on public.role_competencies for all using (public.is_staff()) with check (public.is_staff());

insert into public.roles (name, is_base, sort_order)
select 'Base Nuclear', true, 0
where not exists (select 1 from public.roles where is_base);

-- ============================================================
-- Training catalogue: a training addresses one competency and moves a learner from
-- a lower star to a higher one. Deliverers come from the approved trainers registry.
-- Read/write: staff.
-- ============================================================
create table if not exists public.competency_level_paths (
  competency_id uuid not null references public.competencies(id) on delete cascade,
  level int not null check (level between 1 and 5),
  actions text,
  verification text,
  primary key (competency_id, level)
);
alter table public.competency_level_paths enable row level security;
drop policy if exists clp_read on public.competency_level_paths;
create policy clp_read on public.competency_level_paths for select using (public.is_staff());
drop policy if exists clp_write on public.competency_level_paths;
create policy clp_write on public.competency_level_paths for all using (public.is_staff()) with check (public.is_staff());

create table if not exists public.competency_level_trainings (
  competency_id uuid not null references public.competencies(id) on delete cascade,
  level int not null check (level between 2 and 5),
  training_id uuid not null references public.trainings(id) on delete cascade,
  primary key (competency_id, level, training_id)
);
alter table public.competency_level_trainings enable row level security;
drop policy if exists clt_read on public.competency_level_trainings;
create policy clt_read on public.competency_level_trainings for select using (public.is_staff());
drop policy if exists clt_write on public.competency_level_trainings;
create policy clt_write on public.competency_level_trainings for all using (public.is_staff()) with check (public.is_staff());

create table if not exists public.trainings (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  duration_days numeric,
  notes text,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

-- A training addresses one or more competencies, each with its own star band.
create table if not exists public.training_competencies (
  training_id uuid not null references public.trainings(id) on delete cascade,
  competency_id uuid not null references public.competencies(id) on delete cascade,
  from_level int not null check (from_level between 1 and 4),
  to_level int not null check (to_level between 2 and 5),
  primary key (training_id, competency_id),
  check (from_level < to_level)
);

create table if not exists public.training_deliverers (
  training_id uuid not null references public.trainings(id) on delete cascade,
  trainer_id uuid not null references public.trainers(id) on delete cascade,
  primary key (training_id, trainer_id)
);

alter table public.trainings enable row level security;
alter table public.training_deliverers enable row level security;
drop policy if exists trainings_read on public.trainings;
create policy trainings_read on public.trainings for select using (public.is_staff());
drop policy if exists trainings_write on public.trainings;
create policy trainings_write on public.trainings for all using (public.is_staff()) with check (public.is_staff());
drop policy if exists td_read on public.training_deliverers;
create policy td_read on public.training_deliverers for select using (public.is_staff());
drop policy if exists td_write on public.training_deliverers;
create policy td_write on public.training_deliverers for all using (public.is_staff()) with check (public.is_staff());
drop policy if exists tc_read on public.training_competencies;
create policy tc_read on public.training_competencies for select using (public.is_staff());
drop policy if exists tc_write on public.training_competencies;
create policy tc_write on public.training_competencies for all using (public.is_staff()) with check (public.is_staff());
alter table public.training_competencies enable row level security;

-- =========================================================================
-- Consultant assessments (the consultant-page workflow)
-- =========================================================================
create table if not exists public.assessments (
  id uuid primary key default gen_random_uuid(),
  consultant_id uuid not null references public.consultants(id) on delete cascade,
  status text not null default 'draft'
    check (status in ('draft','self_assessment','validation','planning','plan_review','delivered','cancelled')),
  horizon_months int not null default 18,
  created_by uuid references public.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists assessments_consultant on public.assessments(consultant_id);

create table if not exists public.assessment_roles (
  assessment_id uuid not null references public.assessments(id) on delete cascade,
  role_id uuid not null references public.roles(id) on delete cascade,
  primary key (assessment_id, role_id)
);

alter table public.assessments enable row level security;
alter table public.assessment_roles enable row level security;

drop policy if exists assessments_staff_all on public.assessments;
create policy assessments_staff_all on public.assessments for all using (public.is_staff()) with check (public.is_staff());
drop policy if exists assessments_own_read on public.assessments;
create policy assessments_own_read on public.assessments for select using (
  consultant_id::text = (select u.consultant_id from public.users u where u.id = auth.uid())
);

drop policy if exists ar_staff_all on public.assessment_roles;
create policy ar_staff_all on public.assessment_roles for all using (public.is_staff()) with check (public.is_staff());
drop policy if exists ar_own_read on public.assessment_roles;
create policy ar_own_read on public.assessment_roles for select using (
  exists (
    select 1 from public.assessments a
    join public.users u on u.consultant_id = a.consultant_id::text
    where a.id = assessment_id and u.id = auth.uid()
  )
);
