-- SCHEMA_BASELINE.sql
-- SQEPify schema snapshot. Reference of record.
-- Baseline established: Foundations step (initial).
-- Regenerated by re-extraction (see EXTRACTION_QUERIES.sql), never hand-edited per change.
--
-- This snapshot reflects the database after the Foundations step only.
-- Later tables (consultants, competencies, trainings, assessments, cases, plans)
-- are added in later build-order steps and captured at the next re-baseline.
--
-- Object order matters: the users table is created before the is_superadmin()
-- helper (which reads it), and the helper before the policies (which call it).

-- ============================================================
-- users
-- ============================================================
create table if not exists public.users (
  id            uuid primary key default gen_random_uuid(),
  email         text not null,
  full_name     text,
  product_role  text not null default 'consultant'
                check (product_role in ('superadmin', 'technical_director', 'consultant')),
  consultant_id text,  -- links to the cached consultant record (added in a later step)
  is_active     boolean not null default true,
  created_at    timestamptz not null default now()
);

-- Case-insensitive uniqueness on email (identity is matched by email).
create unique index if not exists users_email_lower_idx
  on public.users (lower(email));

-- ============================================================
-- app_settings (single row: AI provider and model)
-- ============================================================
create table if not exists public.app_settings (
  id          boolean primary key default true check (id),  -- enforces a single row
  ai_provider text not null default 'anthropic'
              check (ai_provider in ('anthropic', 'openai')),
  ai_model    text not null default 'claude-sonnet-4-20250514',
  updated_at  timestamptz not null default now()
);

insert into public.app_settings (id) values (true)
on conflict (id) do nothing;

-- ============================================================
-- Helper: is the caller a superadmin?
-- SECURITY DEFINER so it can read the users table without tripping the table's
-- own RLS (which would otherwise recurse). Matches the caller by email claim.
-- Created after users exists.
-- ============================================================
create or replace function public.is_superadmin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.users u
    where lower(u.email) = lower(auth.jwt() ->> 'email')
      and u.product_role = 'superadmin'
      and u.is_active
  );
$$;

-- ============================================================
-- Row Level Security and policies (created after the helper exists)
-- ============================================================
alter table public.users enable row level security;

drop policy if exists users_select_self on public.users;
create policy users_select_self on public.users
  for select
  using (lower(email) = lower(auth.jwt() ->> 'email'));

drop policy if exists users_all_superadmin on public.users;
create policy users_all_superadmin on public.users
  for all
  using (public.is_superadmin())
  with check (public.is_superadmin());

alter table public.app_settings enable row level security;

drop policy if exists app_settings_select_auth on public.app_settings;
create policy app_settings_select_auth on public.app_settings
  for select
  using (auth.role() = 'authenticated');

drop policy if exists app_settings_write_superadmin on public.app_settings;
create policy app_settings_write_superadmin on public.app_settings
  for all
  using (public.is_superadmin())
  with check (public.is_superadmin());

-- ============================================================
-- consultants (local cache of active consultants from the Control Room feed)
-- Keyed off the Control Room id. Leavers are kept as history (is_active=false),
-- never deleted. Only the sync edge function writes here (service role).
-- ============================================================
create table if not exists public.consultants (
  id                 uuid primary key,
  full_name          text,
  first_name         text,
  last_name          text,
  email              text not null,
  company_email      text,
  job_title          text,
  status             text,
  engineering_skills text[] not null default '{}',
  td_id              uuid,
  td_full_name       text,
  td_email           text,
  is_active          boolean not null default true,
  first_seen_at      timestamptz not null default now(),
  last_seen_at       timestamptz not null default now(),
  left_at            timestamptz,
  updated_at         timestamptz not null default now()
);

create unique index if not exists consultants_company_email_unique
  on public.consultants (lower(company_email)) where company_email is not null;
create index if not exists consultants_td_email_idx on public.consultants (lower(td_email));
create index if not exists consultants_is_active_idx on public.consultants (is_active);

alter table public.consultants enable row level security;

drop policy if exists consultants_select_superadmin on public.consultants;
create policy consultants_select_superadmin on public.consultants
  for select using (public.is_superadmin());

drop policy if exists consultants_select_td on public.consultants;
create policy consultants_select_td on public.consultants
  for select using (lower(td_email) = lower(auth.jwt() ->> 'email'));

drop policy if exists consultants_select_self on public.consultants;
create policy consultants_select_self on public.consultants
  for select using (
    lower(coalesce(company_email, '')) = lower(auth.jwt() ->> 'email')
    or lower(email) = lower(auth.jwt() ->> 'email')
  );

-- ============================================================
-- sync_state (single row: when the consultant sync last ran successfully)
-- Written by the sync edge function (service role). Read-only to the app.
-- ============================================================
create table if not exists public.sync_state (
  id               boolean primary key default true check (id),
  last_sync_at     timestamptz,
  last_pulled      int,
  last_marked_left int,
  updated_at       timestamptz not null default now()
);
insert into public.sync_state (id) values (true) on conflict (id) do nothing;

alter table public.sync_state enable row level security;

drop policy if exists sync_state_select_auth on public.sync_state;
create policy sync_state_select_auth on public.sync_state
  for select using (auth.role() = 'authenticated');
