-- SCHEMA_BASELINE.sql
-- SQEPify schema snapshot. Reference of record.
-- Baseline established: Foundations step (initial).
-- Regenerated by re-extraction (see EXTRACTION_QUERIES.sql), never hand-edited per change.
--
-- This snapshot reflects the database after the Foundations step only.
-- Later tables (consultants, competencies, trainings, assessments, cases, plans)
-- are added in later build-order steps and captured at the next re-baseline.
--
-- Object order matters: the users table is created before the is_superadmin()
-- helper (which reads it), and the helper before the policies (which call it).

-- ============================================================
-- users
-- ============================================================
create table if not exists public.users (
  id            uuid primary key default gen_random_uuid(),
  email         text not null,
  full_name     text,
  product_role  text not null default 'consultant'
                check (product_role in ('superadmin', 'technical_director', 'consultant')),
  consultant_id text,  -- links to the cached consultant record (added in a later step)
  is_active     boolean not null default true,
  created_at    timestamptz not null default now()
);

-- Case-insensitive uniqueness on email (identity is matched by email).
create unique index if not exists users_email_lower_idx
  on public.users (lower(email));

-- ============================================================
-- app_settings (key/value; read by the AI client and editable by the superadmin)
-- ============================================================
create table if not exists public.app_settings (
  key        text primary key,
  value      text,
  updated_at timestamptz not null default now()
);

insert into public.app_settings (key, value) values
  ('ai_primary_provider', 'anthropic'),
  ('ai_model_anthropic',  'claude-sonnet-4-6'),
  ('ai_model_openai',     'gpt-4o')
on conflict (key) do nothing;

-- ============================================================
-- Helper: is the caller a superadmin?
-- SECURITY DEFINER so it can read the users table without tripping the table's
-- own RLS (which would otherwise recurse). Matches the caller by email claim.
-- Created after users exists.
-- ============================================================
create or replace function public.is_superadmin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.users u
    where lower(u.email) = lower(auth.jwt() ->> 'email')
      and u.product_role = 'superadmin'
      and u.is_active
  );
$$;

-- ============================================================
-- Row Level Security and policies (created after the helper exists)
-- ============================================================
alter table public.users enable row level security;

drop policy if exists users_select_self on public.users;
create policy users_select_self on public.users
  for select
  using (lower(email) = lower(auth.jwt() ->> 'email'));

drop policy if exists users_all_superadmin on public.users;
create policy users_all_superadmin on public.users
  for all
  using (public.is_superadmin())
  with check (public.is_superadmin());

alter table public.app_settings enable row level security;

drop policy if exists app_settings_select_auth on public.app_settings;
create policy app_settings_select_auth on public.app_settings
  for select
  using (auth.role() = 'authenticated');

drop policy if exists app_settings_write_superadmin on public.app_settings;
create policy app_settings_write_superadmin on public.app_settings
  for all
  using (public.is_superadmin())
  with check (public.is_superadmin());

-- ============================================================
-- consultants (local cache of active consultants from the Control Room feed)
-- Keyed off the Control Room id. Leavers are kept as history (is_active=false),
-- never deleted. Only the sync edge function writes here (service role).
-- ============================================================
create table if not exists public.consultants (
  id                 uuid primary key,
  full_name          text,
  first_name         text,
  last_name          text,
  email              text not null,
  company_email      text,
  job_title          text,
  status             text,
  engineering_skills text[] not null default '{}',
  td_id              uuid,
  td_full_name       text,
  td_email           text,
  is_active          boolean not null default true,
  first_seen_at      timestamptz not null default now(),
  last_seen_at       timestamptz not null default now(),
  left_at            timestamptz,
  updated_at         timestamptz not null default now()
);

create unique index if not exists consultants_company_email_unique
  on public.consultants (lower(company_email)) where company_email is not null;
create index if not exists consultants_td_email_idx on public.consultants (lower(td_email));
create index if not exists consultants_is_active_idx on public.consultants (is_active);

alter table public.consultants enable row level security;

drop policy if exists consultants_select_superadmin on public.consultants;
create policy consultants_select_superadmin on public.consultants
  for select using (public.is_superadmin());

drop policy if exists consultants_select_td on public.consultants;
create policy consultants_select_td on public.consultants
  for select using (lower(td_email) = lower(auth.jwt() ->> 'email'));

drop policy if exists consultants_select_self on public.consultants;
create policy consultants_select_self on public.consultants
  for select using (
    lower(coalesce(company_email, '')) = lower(auth.jwt() ->> 'email')
    or lower(email) = lower(auth.jwt() ->> 'email')
  );

-- ============================================================
-- sync_state (single row: when the consultant sync last ran successfully)
-- Written by the sync edge function (service role). Read-only to the app.
-- ============================================================
create table if not exists public.sync_state (
  id               boolean primary key default true check (id),
  last_sync_at     timestamptz,
  last_pulled      int,
  last_marked_left int,
  updated_at       timestamptz not null default now()
);
insert into public.sync_state (id) values (true) on conflict (id) do nothing;

alter table public.sync_state enable row level security;

drop policy if exists sync_state_select_auth on public.sync_state;
create policy sync_state_select_auth on public.sync_state
  for select using (auth.role() = 'authenticated');

-- ============================================================
-- reconcile_consultant_users()
-- Called at the end of each consultant sync. Creates a SQEPify login for each
-- active consultant that has a company email, links existing logins, reactivates
-- returning consultants, and switches off the logins of consultants who have left.
-- Only ever affects consultant-role accounts; never a TD or superadmin.
-- ============================================================
create or replace function public.reconcile_consultant_users()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (email, full_name, product_role, is_active, consultant_id)
  select c.company_email, c.full_name, 'consultant', true, c.id::text
  from public.consultants c
  where c.is_active
    and c.company_email is not null
    and not exists (select 1 from public.users u where lower(u.email) = lower(c.company_email));

  update public.users u
  set consultant_id = c.id::text,
      is_active = case when u.product_role = 'consultant' then true else u.is_active end
  from public.consultants c
  where c.is_active and c.company_email is not null
    and lower(u.email) = lower(c.company_email);

  update public.users u
  set is_active = false
  from public.consultants c
  where u.product_role = 'consultant'
    and u.consultant_id = c.id::text
    and c.is_active = false;
end;
$$;

-- ============================================================
-- is_staff(): caller is a superadmin or a technical director (active)
-- ============================================================
create or replace function public.is_staff()
returns boolean language sql security definer set search_path = public as $$
  select exists (
    select 1 from public.users u
    where lower(u.email) = lower(auth.jwt() ->> 'email')
      and u.product_role in ('superadmin','technical_director')
      and u.is_active
  );
$$;

-- ============================================================
-- trainers (approved trainers registry: TDs, consultants, external providers)
-- A training may only list deliverers that appear here.
-- ============================================================
create table if not exists public.trainers (
  id            uuid primary key default gen_random_uuid(),
  kind          text not null check (kind in ('technical_director','consultant','external')),
  user_id       uuid,
  consultant_id text,
  display_name  text not null,
  company_name  text,
  contact_name  text,
  contact_email text,
  contact_phone text,
  notes         text,
  is_active     boolean not null default true,
  created_at    timestamptz not null default now()
);
create unique index if not exists trainers_user_unique on public.trainers (user_id) where user_id is not null;
create unique index if not exists trainers_consultant_unique on public.trainers (consultant_id) where consultant_id is not null;

alter table public.trainers enable row level security;

drop policy if exists trainers_select_staff on public.trainers;
create policy trainers_select_staff on public.trainers for select using (public.is_staff());

drop policy if exists trainers_write_superadmin on public.trainers;
drop policy if exists trainers_write_staff on public.trainers;
create policy trainers_write_staff on public.trainers
  for all using (public.is_staff()) with check (public.is_staff());

-- Guarded lookup so staff can pick trainers without the user/consultant tables being opened up
create or replace function public.trainer_candidates()
returns table (kind text, id text, name text)
language sql security definer set search_path = public as $$
  select 'td'::text, u.id::text, coalesce(u.full_name, u.email)
  from public.users u
  where public.is_staff() and u.product_role = 'technical_director' and u.is_active
  union all
  select 'consultant'::text, c.id::text, coalesce(c.full_name, c.company_email, c.email)
  from public.consultants c
  where public.is_staff() and c.is_active;
$$;
grant execute on function public.trainer_candidates() to authenticated;

-- ============================================================
-- Competency taxonomy: category -> optional subcategory -> competency
-- Read: any signed-in user. Write: staff (superadmin or technical director).
-- ============================================================
create table if not exists public.competency_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists public.competency_subcategories (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.competency_categories(id) on delete cascade,
  name text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists public.competencies (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.competency_categories(id) on delete cascade,
  subcategory_id uuid references public.competency_subcategories(id) on delete set null,
  name text not null,
  description text,
  level_descriptors jsonb,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists competency_subcategories_category on public.competency_subcategories(category_id);
create index if not exists competencies_category on public.competencies(category_id);
create index if not exists competencies_subcategory on public.competencies(subcategory_id);

alter table public.competency_categories enable row level security;
alter table public.competency_subcategories enable row level security;
alter table public.competencies enable row level security;

drop policy if exists comp_cat_read on public.competency_categories;
create policy comp_cat_read on public.competency_categories for select using (auth.role() = 'authenticated');
drop policy if exists comp_cat_write on public.competency_categories;
create policy comp_cat_write on public.competency_categories for all using (public.is_staff()) with check (public.is_staff());

drop policy if exists comp_sub_read on public.competency_subcategories;
create policy comp_sub_read on public.competency_subcategories for select using (auth.role() = 'authenticated');
drop policy if exists comp_sub_write on public.competency_subcategories;
create policy comp_sub_write on public.competency_subcategories for all using (public.is_staff()) with check (public.is_staff());

drop policy if exists comp_read on public.competencies;
create policy comp_read on public.competencies for select using (auth.role() = 'authenticated');
drop policy if exists comp_write on public.competencies;
create policy comp_write on public.competencies for all using (public.is_staff()) with check (public.is_staff());

-- ============================================================
-- Roles: named sets of competencies. Base Nuclear is the always-present base.
-- A competency in Base cannot be in any other role (and vice versa); normal roles
-- may share competencies. Read: staff. Write: staff. Base role is protected.
-- ============================================================
create table if not exists public.roles (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  is_base boolean not null default false,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);
create unique index if not exists roles_single_base on public.roles ((is_base)) where is_base;

create table if not exists public.role_competencies (
  role_id uuid not null references public.roles(id) on delete cascade,
  competency_id uuid not null references public.competencies(id) on delete cascade,
  required_level int not null default 4 check (required_level between 1 and 5),
  created_at timestamptz not null default now(),
  primary key (role_id, competency_id)
);

create or replace function public.protect_base_role() returns trigger language plpgsql as $$
begin
  if tg_op = 'DELETE' then
    if old.is_base then raise exception 'The Base Nuclear role cannot be deleted.'; end if;
    return old;
  end if;
  if old.is_base and not new.is_base then raise exception 'The Base Nuclear role must remain the base.'; end if;
  return new;
end $$;
drop trigger if exists trg_protect_base_role on public.roles;
create trigger trg_protect_base_role before update or delete on public.roles
  for each row execute function public.protect_base_role();

create or replace function public.enforce_role_exclusivity() returns trigger language plpgsql as $$
declare target_is_base boolean;
begin
  select is_base into target_is_base from public.roles where id = new.role_id;
  if target_is_base then
    if exists (select 1 from public.role_competencies rc join public.roles r on r.id = rc.role_id
               where rc.competency_id = new.competency_id and not r.is_base) then
      raise exception 'This competency is in a role already; remove it before adding to Base Nuclear.';
    end if;
  else
    if exists (select 1 from public.role_competencies rc join public.roles r on r.id = rc.role_id
               where rc.competency_id = new.competency_id and r.is_base) then
      raise exception 'This competency is in Base Nuclear and cannot be added to a role.';
    end if;
  end if;
  return new;
end $$;
drop trigger if exists trg_role_exclusivity on public.role_competencies;
create trigger trg_role_exclusivity before insert on public.role_competencies
  for each row execute function public.enforce_role_exclusivity();

alter table public.roles enable row level security;
alter table public.role_competencies enable row level security;
drop policy if exists roles_read on public.roles;
create policy roles_read on public.roles for select using (auth.role() = 'authenticated');
drop policy if exists roles_write on public.roles;
create policy roles_write on public.roles for all using (public.is_staff()) with check (public.is_staff());
drop policy if exists rc_read on public.role_competencies;
create policy rc_read on public.role_competencies for select using (auth.role() = 'authenticated');
drop policy if exists rc_write on public.role_competencies;
create policy rc_write on public.role_competencies for all using (public.is_staff()) with check (public.is_staff());

insert into public.roles (name, is_base, sort_order)
select 'Base Nuclear', true, 0
where not exists (select 1 from public.roles where is_base);

-- ============================================================
-- Training catalogue: a training addresses one competency and moves a learner from
-- a lower star to a higher one. Deliverers come from the approved trainers registry.
-- Read/write: staff.
-- ============================================================
create table if not exists public.competency_level_paths (
  competency_id uuid not null references public.competencies(id) on delete cascade,
  level int not null check (level between 1 and 5),
  actions text,
  verification text,
  primary key (competency_id, level)
);
alter table public.competency_level_paths enable row level security;
drop policy if exists clp_read on public.competency_level_paths;
create policy clp_read on public.competency_level_paths for select using (public.is_staff());
drop policy if exists clp_write on public.competency_level_paths;
create policy clp_write on public.competency_level_paths for all using (public.is_staff()) with check (public.is_staff());

create table if not exists public.competency_level_trainings (
  competency_id uuid not null references public.competencies(id) on delete cascade,
  level int not null check (level between 2 and 5),
  training_id uuid not null references public.trainings(id) on delete cascade,
  primary key (competency_id, level, training_id)
);
alter table public.competency_level_trainings enable row level security;
drop policy if exists clt_read on public.competency_level_trainings;
create policy clt_read on public.competency_level_trainings for select using (public.is_staff());
drop policy if exists clt_write on public.competency_level_trainings;
create policy clt_write on public.competency_level_trainings for all using (public.is_staff()) with check (public.is_staff());

create table if not exists public.trainings (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  duration_hours int,
  status text not null default 'active' check (status in ('active','required')),
  notes text,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);
-- The competency-to-training mapping lives in the learning path
-- (competency_level_trainings), not on the training itself.

create table if not exists public.training_deliverers (
  training_id uuid not null references public.trainings(id) on delete cascade,
  trainer_id uuid not null references public.trainers(id) on delete cascade,
  primary key (training_id, trainer_id)
);

alter table public.trainings enable row level security;
alter table public.training_deliverers enable row level security;
drop policy if exists trainings_read on public.trainings;
create policy trainings_read on public.trainings for select using (public.is_staff());
drop policy if exists trainings_write on public.trainings;
create policy trainings_write on public.trainings for all using (public.is_staff()) with check (public.is_staff());
drop policy if exists td_read on public.training_deliverers;
create policy td_read on public.training_deliverers for select using (public.is_staff());
drop policy if exists td_write on public.training_deliverers;
create policy td_write on public.training_deliverers for all using (public.is_staff()) with check (public.is_staff());

-- =========================================================================
-- Consultant assessments (the consultant-page workflow)
-- =========================================================================
create table if not exists public.assessments (
  id uuid primary key default gen_random_uuid(),
  consultant_id uuid not null references public.consultants(id) on delete cascade,
  status text not null default 'draft'
    check (status in ('draft','self_assessment','validation','planning','plan_review','delivered','cancelled')),
  horizon_months int not null default 18,
  created_by uuid references public.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists assessments_consultant on public.assessments(consultant_id);

create table if not exists public.assessment_roles (
  assessment_id uuid not null references public.assessments(id) on delete cascade,
  role_id uuid not null references public.roles(id) on delete cascade,
  primary key (assessment_id, role_id)
);

alter table public.assessments enable row level security;
alter table public.assessment_roles enable row level security;

drop policy if exists assessments_staff_all on public.assessments;
create policy assessments_staff_all on public.assessments for all using (public.is_staff()) with check (public.is_staff());
drop policy if exists assessments_own_read on public.assessments;
create policy assessments_own_read on public.assessments for select using (
  consultant_id::text = (select u.consultant_id from public.users u where lower(u.email) = lower(auth.jwt() ->> 'email'))
);

drop policy if exists ar_staff_all on public.assessment_roles;
create policy ar_staff_all on public.assessment_roles for all using (public.is_staff()) with check (public.is_staff());
drop policy if exists ar_own_read on public.assessment_roles;
create policy ar_own_read on public.assessment_roles for select using (
  exists (
    select 1 from public.assessments a
    join public.users u on u.consultant_id = a.consultant_id::text
    where a.id = assessment_id and lower(u.email) = lower(auth.jwt() ->> 'email')
  )
);
create table if not exists public.assessment_scores (
  assessment_id uuid not null references public.assessments(id) on delete cascade,
  competency_id uuid not null references public.competencies(id) on delete cascade,
  ai_level int check (ai_level between 0 and 5),
  self_level int check (self_level between 0 and 5),
  validated_level int check (validated_level between 0 and 5),
  note text,
  primary key (assessment_id, competency_id)
);
alter table public.assessment_scores enable row level security;
drop policy if exists as_staff_all on public.assessment_scores;
create policy as_staff_all on public.assessment_scores for all using (public.is_staff()) with check (public.is_staff());
drop policy if exists as_own_rw on public.assessment_scores;
create policy as_own_rw on public.assessment_scores for all using (
  exists (
    select 1 from public.assessments a
    join public.users u on u.consultant_id = a.consultant_id::text
    where a.id = assessment_id and lower(u.email) = lower(auth.jwt() ->> 'email')
  )
) with check (
  exists (
    select 1 from public.assessments a
    join public.users u on u.consultant_id = a.consultant_id::text
    where a.id = assessment_id and lower(u.email) = lower(auth.jwt() ->> 'email')
  )
);
create table if not exists public.plan_items (
  id uuid primary key default gen_random_uuid(),
  assessment_id uuid not null references public.assessments(id) on delete cascade,
  competency_id uuid not null references public.competencies(id) on delete cascade,
  training_id uuid references public.trainings(id) on delete set null,
  title text,
  from_level int not null default 0,
  to_level int not null default 0,
  start_month int not null default 0,
  duration_months int not null default 1,
  status text not null default 'planned' check (status in ('planned','training_done','confirmed','blocked')),
  outcome_level int check (outcome_level between 0 and 5),
  note text,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists plan_items_assessment on public.plan_items(assessment_id);
alter table public.plan_items enable row level security;
drop policy if exists pi_staff_all on public.plan_items;
create policy pi_staff_all on public.plan_items for all using (public.is_staff()) with check (public.is_staff());
drop policy if exists pi_own_read on public.plan_items;
create policy pi_own_read on public.plan_items for select using (
  exists (select 1 from public.assessments a join public.users u on u.consultant_id = a.consultant_id::text
    where a.id = assessment_id and lower(u.email) = lower(auth.jwt() ->> 'email'))
);

-- ============================================================
-- Delivery workflow: plan_items v2 + plan_item_outcomes (Step 1)
-- ============================================================
-- plan_items v2
alter table public.plan_items add column if not exists kind text not null default 'training';
do $$ begin
  if not exists (select 1 from pg_constraint where conname='plan_items_kind_chk') then
    alter table public.plan_items add constraint plan_items_kind_chk check (kind in ('training','missing'));
  end if;
end $$;
alter table public.plan_items add column if not exists trainer_id uuid references public.trainers(id) on delete set null;
alter table public.plan_items add column if not exists delivered_at timestamptz;
alter table public.plan_items add column if not exists delivered_by uuid references public.users(id);
alter table public.plan_items add column if not exists assessed_at timestamptz;
alter table public.plan_items add column if not exists assessed_by uuid references public.users(id);
alter table public.plan_items alter column competency_id drop not null;
alter table public.plan_items alter column start_month drop not null;
update public.plan_items set status='delivered' where status='training_done';
update public.plan_items set status='assessed' where status='confirmed';
do $$
declare c record;
begin
  for c in select conname from pg_constraint where conrelid='public.plan_items'::regclass and contype='c'
           and pg_get_constraintdef(oid) ilike '%status%' loop
    execute format('alter table public.plan_items drop constraint %I', c.conname);
  end loop;
end $$;
do $$ begin
  if not exists (select 1 from pg_constraint where conname='plan_items_status_chk') then
    alter table public.plan_items add constraint plan_items_status_chk check (status in ('planned','delivered','assessed','blocked'));
  end if;
end $$;
create index if not exists plan_items_trainer on public.plan_items(trainer_id);

-- per-delivery reassessment outcomes (history in the diamond card)
create table if not exists public.plan_item_outcomes (
  id uuid primary key default gen_random_uuid(),
  plan_item_id uuid not null references public.plan_items(id) on delete cascade,
  competency_id uuid not null references public.competencies(id) on delete cascade,
  level int not null check (level between 0 and 5),
  created_at timestamptz not null default now()
);
create index if not exists plan_item_outcomes_item on public.plan_item_outcomes(plan_item_id);
alter table public.plan_item_outcomes enable row level security;
drop policy if exists pio_staff_all on public.plan_item_outcomes;
create policy pio_staff_all on public.plan_item_outcomes for all using (public.is_staff()) with check (public.is_staff());
drop policy if exists pio_own_read on public.plan_item_outcomes;
create policy pio_own_read on public.plan_item_outcomes for select using (
  exists (select 1 from public.plan_items pi join public.assessments a on a.id = pi.assessment_id
    join public.users u on u.consultant_id = a.consultant_id::text
    where pi.id = plan_item_id and lower(u.email) = lower(auth.jwt() ->> 'email'))
);

-- trainers can see the diamonds assigned to them
drop policy if exists pi_trainer_read on public.plan_items;
create policy pi_trainer_read on public.plan_items for select using (
  exists (select 1 from public.trainers t join public.users u on u.id = t.user_id
    where t.id = trainer_id and lower(u.email) = lower(auth.jwt() ->> 'email'))
);
-- ============================================================
-- Step 3: trainer delivery RPCs
-- ============================================================
-- Step 3: trainer delivery RPCs (security definer; keep RLS narrow)
drop function if exists public.my_delivery_assignments();
create or replace function public.my_delivery_assignments()
returns table (
  plan_item_id uuid, training_id uuid, start_month int, status text,
  consultant_id text, consultant_name text, td_full_name text, td_email text
)
language sql security definer set search_path = public stable as $$
  select pi.id, pi.training_id, pi.start_month, pi.status,
         c.id::text, coalesce(nullif(c.full_name, ''), c.email) as consultant_name,
         c.td_full_name, c.td_email
  from public.plan_items pi
  join public.trainers t on t.id = pi.trainer_id
  join public.users me on me.id = t.user_id
  join public.assessments a on a.id = pi.assessment_id
  join public.consultants c on c.id = a.consultant_id
  where pi.kind = 'training' and pi.training_id is not null
    and lower(me.email) = lower(auth.jwt() ->> 'email');
$$;
grant execute on function public.my_delivery_assignments() to authenticated;

create or replace function public.mark_training_delivered(p_plan_item_id uuid)
returns void language plpgsql security definer set search_path = public as $$
declare me uuid;
begin
  select u.id into me from public.users u where lower(u.email) = lower(auth.jwt() ->> 'email');
  if me is null then raise exception 'no application user for this account'; end if;
  if not exists (
    select 1 from public.plan_items pi join public.trainers t on t.id = pi.trainer_id
    where pi.id = p_plan_item_id and t.user_id = me
  ) then
    raise exception 'not authorised to mark this training delivered';
  end if;
  update public.plan_items
     set status = 'delivered', delivered_at = now(), delivered_by = me
   where id = p_plan_item_id and status = 'planned';
end; $$;
grant execute on function public.mark_training_delivered(uuid) to authenticated;
-- ============================================================
-- Step 6: trainer move requests
-- ============================================================
-- Step 6: trainer move requests
create table if not exists public.plan_move_requests (
  id uuid primary key default gen_random_uuid(),
  plan_item_id uuid not null references public.plan_items(id) on delete cascade,
  requested_month int not null,
  requested_by uuid references public.users(id),
  status text not null default 'pending' check (status in ('pending','accepted','declined')),
  decided_by uuid references public.users(id),
  decided_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists plan_move_requests_item on public.plan_move_requests(plan_item_id);
create index if not exists plan_move_requests_status on public.plan_move_requests(status);
alter table public.plan_move_requests enable row level security;
drop policy if exists pmr_staff_all on public.plan_move_requests;
create policy pmr_staff_all on public.plan_move_requests for all using (public.is_staff()) with check (public.is_staff());
drop policy if exists pmr_trainer_read on public.plan_move_requests;
create policy pmr_trainer_read on public.plan_move_requests for select using (
  exists (select 1 from public.plan_items pi join public.trainers t on t.id = pi.trainer_id
    join public.users u on u.id = t.user_id
    where pi.id = plan_item_id and lower(u.email) = lower(auth.jwt() ->> 'email'))
);

-- assignments RPC now also reports any pending move month
drop function if exists public.my_delivery_assignments();
create or replace function public.my_delivery_assignments()
returns table (
  plan_item_id uuid, training_id uuid, start_month int, status text,
  consultant_id text, consultant_name text, td_full_name text, td_email text, pending_month int
)
language sql security definer set search_path = public stable as $$
  select pi.id, pi.training_id, pi.start_month, pi.status,
         c.id::text, coalesce(nullif(c.full_name, ''), c.email) as consultant_name,
         c.td_full_name, c.td_email, pm.requested_month
  from public.plan_items pi
  join public.trainers t on t.id = pi.trainer_id
  join public.users me on me.id = t.user_id
  join public.assessments a on a.id = pi.assessment_id
  join public.consultants c on c.id = a.consultant_id
  left join lateral (
    select r.requested_month from public.plan_move_requests r
    where r.plan_item_id = pi.id and r.status = 'pending' order by r.created_at desc limit 1
  ) pm on true
  where pi.kind = 'training' and pi.training_id is not null
    and lower(me.email) = lower(auth.jwt() ->> 'email');
$$;
grant execute on function public.my_delivery_assignments() to authenticated;

create or replace function public.request_training_move(p_plan_item_id uuid, p_month int)
returns void language plpgsql security definer set search_path = public as $$
declare me uuid;
begin
  select u.id into me from public.users u where lower(u.email) = lower(auth.jwt() ->> 'email');
  if not exists (select 1 from public.plan_items pi join public.trainers t on t.id = pi.trainer_id where pi.id = p_plan_item_id and t.user_id = me) then
    raise exception 'not authorised to request a move for this training';
  end if;
  update public.plan_move_requests set status = 'declined', decided_at = now() where plan_item_id = p_plan_item_id and status = 'pending';
  insert into public.plan_move_requests (plan_item_id, requested_month, requested_by) values (p_plan_item_id, p_month, me);
end; $$;
grant execute on function public.request_training_move(uuid, int) to authenticated;

create or replace function public.decide_training_move(p_request_id uuid, p_accept boolean)
returns void language plpgsql security definer set search_path = public as $$
declare me uuid; v_item uuid; v_month int;
begin
  select u.id into me from public.users u where lower(u.email) = lower(auth.jwt() ->> 'email');
  select plan_item_id, requested_month into v_item, v_month from public.plan_move_requests where id = p_request_id and status = 'pending';
  if v_item is null then raise exception 'no pending request'; end if;
  -- only the consultant's responsible TD, or a superadmin, may decide
  if not (public.is_superadmin() or exists (
    select 1 from public.plan_items pi join public.assessments a on a.id = pi.assessment_id
      join public.consultants c on c.id = a.consultant_id
    where pi.id = v_item and lower(c.td_email) = lower(auth.jwt() ->> 'email'))) then
    raise exception 'not authorised to decide this request';
  end if;
  if p_accept then
    update public.plan_items set start_month = v_month where id = v_item;
    update public.plan_move_requests set status = 'accepted', decided_by = me, decided_at = now() where id = p_request_id;
  else
    update public.plan_move_requests set status = 'declined', decided_by = me, decided_at = now() where id = p_request_id;
  end if;
end; $$;
grant execute on function public.decide_training_move(uuid, boolean) to authenticated;
